### ISSUE TITLE
Small type in Chapter 3

### ISSUE THREAD

**Issue by farazdurrani** [Apress/pro-spring-5#10]
In chapter 3, on page 87, there is a small type. 

It should be "For abstractLookupBean..." instead of "For abstract-LookupBean...".

And on page 89, It should be "@Component("singer")" instead of "@Component("singler)" (missing closing quote).

**Comment by iuliana** [comment]
Thank you for your contribution. An entry has been added to the Errata about it.

**Comment by farazdurrani** [comment]
@iuliana please add this as well. On page 94, on 3rd line, it says replacementTargetBean. It should be ReplacementTarget bean or replacementTarget bean.

**Comment by iuliana** [comment]
Github is for problems in the code. GitHub is spamming me, please make a list of issues you find and send it to me via email. (iuliana.cosmina@gmail.com)
