### ISSUE TITLE
Error in Chapter 3 - AnnotatedBeanNaming

### ISSUE THREAD

**Issue by daniel-rocha** [Apress/pro-spring-5#14]
Without annotating Award with
```
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
```
The AnnotatedBeanNaming class will fail with: 

_An exception occured while executing the Java class. Unexpected exception parsing XML document from class path resource [spring/app-context-annotated.xml]; nested exception is org.springframework.core.annotation.AnnotationConfigurationException: @AliasFor declaration on attribute 'name' in annotation [com.apress.prospring5.ch3.annotated.Trophy] declares an alias for attribute 'value' in meta-annotation [com.apress.prospring5.ch3.annotated.Award] which is not meta-present. -> [Help 1]_

**Comment by EXL** [comment]
@daniel-rocha I also encountered this problem. Has anyone found a solution?

**Comment by iuliana** [comment]
Hello, 
Commit https://github.com/Apress/pro-spring-5/commit/a859ee82a066f7b7f38c30697bc9339067790d28  fixes the issue. 

Sorry I did not have the time to look at this earlier. 

Cheers, 
Iuliana
