### ISSUE TITLE
How to import to Spring STS.

### ISSUE THREAD

**Issue by softcontext** [Apress/pro-spring-5#2]
I want to import demo projects to Spring STS.
I have tried various methods that I learned through googling.
But, all failed.
Do i have to use IDEA?
I wonder if you can help me.
Good day!

**Comment by iuliana** [comment]
Hello, 

STS does not include a Gradle plugin. Install that first and then load the project.  You can find instructions how to do that here: [http://www.vogella.com/tutorials/EclipseGradle/article.html](http://www.vogella.com/tutorials/EclipseGradle/article.html)
Then use File ▸ Import…​ ▸ Gradle ▸ Gradle Project menu and choose the pro-spring-5 directory.  The whole process of installing the plugin, scanning all modules, refreshing the interface, update took about 20 minutes.

I updated the configuration so it will work on STS too, apparently for some reason the root directory name must be the same with the project name in STS.

Thought I strongly recommend IntelliJ IDEA as an editor. When you install it make sure you choose the Gradle plugin from the list of build tools plugins and when your project will be loaded quite quickly.

**Comment by softcontext** [comment]
I appreciate your response.
I am an instructor in a small academy.
The academy can not afford to use non-free software.
I want to open a new class of Spring 5.
So, I am searching good materials for the class.
I will try your advice, thank you.

2018-01-21 21:37 GMT+09:00 Iuliana Cosmina <notifications@github.com>:
