### ISSUE TITLE
Using AbstractAnnotationConfigDispatcherServletInitializer to configure multiple DispatcherServlet

### ISSUE THREAD

**Issue by SIJH** [Apress/pro-spring-5#22]
In Chapter 16 of Pro Spring 5, quote, "In a Spring MVC application, there can be any number of DispatcherServlet
instances for various purposes." Most of the Spring MVC example codes in the book use a class extending  AbstractAnnotationConfigDispatcherServletInitializer to configure a DispatcherServlet. May I ask if and how multiple DispatcherServlets can be configured using a class extending AbstractAnnotationConfigDispatcherServletInitializer? Or how to configure multiple DispatcherServlets with Java-based configuration class? I googled and checked the reference on Spring website and failed to find the answer. Thank you!

**Comment by iuliana** [comment]
Hello SIJH, 

Thnk you for your interest in my book. Unfortunately I do not have an example handly. 
I can try to wrap up something, but I have another book to finish right now. 

I do not think the `AbstractAnnotationConfigDispatcherServletInitializer` class  is suitable for that. But you can use the `WebApplicationInitializer` interface. Implement this interface and in the body of the  `onStartup(...)` you might be able to do something like in the following example: 

```
// Create the dispatcher servlet's Spring application context
      AnnotationConfigWebApplicationContext dispatcherContext = new AnnotationConfigWebApplicationContext();
      dispatcherContext.register(DispatcherConfig.class);

  // Register and map the dispatcher1 servlet
      ServletRegistration.Dynamic dispatcher1 = container.addServlet("dispatcher1", new DispatcherServlet(dispatcherContext));
      dispatcher1.setLoadOnStartup(1);
      dispatcher1.addMapping("/dispatcher1");

 ServletRegistration.Dynamic  dispatcher2 = container.addServlet("dispatcher2", new DispatcherServlet(dispatcherContext));
      dispatcher2.setLoadOnStartup(1);
      dispatcher2.addMapping("/dispatcher2");
```
I am sorry I do not have the time to look more into this. Let me know if works like this. 
Cheers, 
Iuliana Cosmina

**Comment by SIJH** [comment]
Hi Iuliana, 

 Thank you a lot for your answer. I haven't check it yet but it makes much sense. I am looking forward to your new book. 

Cheers,
Jinhua

**Comment by iuliana** [comment]
👍
