### ISSUE TITLE
Chapter 5  section "Creating Throws Advice"

### ISSUE THREAD

**Issue by rafalnowicki116** [Apress/pro-spring-5#23]
Hello Iuliana,

In your book Spring Pro5 you have one sentence:
"In the situation where your after-throwing advice has two afterThrowing() methods, both declared with the same Exception type but one with with a single argument and the other with four arguments, Spring invokes the four-argument afterThrowing() method."

I've checked this situation and it seems that it works the other way around (under certain conditions).  

**Source code:**
```
public class SimpleThrowsAdvice implements ThrowsAdvice {
    public static void main(String[] args) throws Exception {
        ErrorBean errorBean = new ErrorBean();
        ProxyFactory pf = new ProxyFactory();
        pf.setTarget(errorBean);
        pf.addAdvice(new SimpleThrowsAdvice());
        ErrorBean proxy = (ErrorBean) pf.getProxy();
        try {
            proxy.errorProneMethod();
        } catch (Exception ignored) {
        }
        try {
            proxy.otherErrorProneMethod();
        } catch (Exception ignored) {
        }
    }
    public void afterThrowing(Exception ex) throws Throwable {
        System.out.println("***");
        System.out.println("One argument");
        System.out.println(ex.getMessage() + " Captured");
        System.out.println("***\n");
    }
    public void afterThrowing(Method method, Object[] args,
                              Object target, Exception ex) throws Throwable {
        System.out.println("***");
        System.out.println("Four arguments");
        System.out.println(ex.getMessage() + " Captured");
        System.out.println("***\n");
    }
    public void afterThrowing(Method method, Object[] args, Object target,
                              IllegalArgumentException ex) throws Throwable {
        System.out.println("***");
        System.out.println("IllegalArgumentException Capture");
        System.out.println("Caught: " + ex.getClass().getName());
        System.out.println("Method: " + method.getName());
        System.out.println("***\n");
    }
}
```
**Output:** 
`***
One argument
Generic Exception Captured
***

***
IllegalArgumentException Capture
Caught: java.lang.IllegalArgumentException
Method: otherErrorProneMethod
***`

What is more when we change the order of afterThrowing methods then it works as you mentioned in the book. 

Is it a bug in Spring?

Thanks in advance,

BR,
Rafał Nowicki

**Comment by iuliana** [comment]
Hello @rafalnowicki116 , 

This book has four authors, I don't think the code or text is mine, but I will look into it because you made me curious :D. 
But I doubt this is  Spring bug.  I incline to think it might be wrong phrasing. 

Cheers, 
Iuliana

**Comment by iuliana** [comment]
Hello @rafalnowicki116, 

I admit the text in the book is a little bit confusing. The phrase you should be interested in is: 
` Spring invokes a afterThrowing() method for each Exception, and as you saw from the example in class SimpleThrowsAdviceSpring, uses the method whose signature contains the best match for the Exception type.`

The documentation for `ThrowsAdvice` in Spring 5 doesn't say anything similar to the phrase you mentioned and that appears in the book.  I might have copied that from the previos edition of the book and did not check it as well as I should. (Maybe this was valid for Spring 4, maybe the original author got it wrong.)

No bug in Spring, just bug in the book.  :) Awesome obervation, I added a mention in the book erratum. 
Commit with errata entry and contribution mention: [https://github.com/Apress/pro-spring-5/commit/482c63afa30943c908e0f54457689292f8182784](https://github.com/Apress/pro-spring-5/commit/482c63afa30943c908e0f54457689292f8182784)

Thank you so much for this! 
Iuliana
