### ISSUE TITLE
NamePointcutUsingAdvisor

### ISSUE THREAD

**Issue by yyi** [Apress/pro-spring-5#4]
com.apress.prospring5.ch5.NamePointcutUsingAdvisor  should add proxy method names:
NameMatchMethodPointcutAdvisor advisor = new NameMatchMethodPointcutAdvisor(new SimpleAdvice());
advisor.setMappedNames("sing","rest");

**Comment by iuliana** [comment]
Hello yyi, 

Yap, you are right. No idea what happened there. It seems I just duplicated the code from the previous section "Creating Annotation Matching Pointcuts". 

I modified the code, pushed the changes and I updated the Errata too.  Thank you very much for helping me correct the code and the book.

**Comment by iuliana** [comment]
Fixed the code, no feedback yet from reporter. But I trust myself enough to close this. ;)
