### ISSUE TITLE
There is no PasswordEncoder mapped for the id "null"

### ISSUE THREAD

**Issue by cbot59** [Apress/pro-spring-5#5]
Chapter 16: singer-webapp-boot

Cannot login because "There is no PasswordEncoder mapped for the id "null"

Need to specify id of PasswordEncoder, please refer to this: https://spring.io/blog/2017/11/01/spring-security-5-0-0-rc1-released

**Comment by iuliana** [comment]
Hi cbot59, 
Thank you for this. I must have used an older Spring Boot version when not having a Password encoder was allowed.  I will try to disable this or add a Password Encoder and update the sources and the book. 

Cheers!

**Comment by iuliana** [comment]
The last commit contains a version that uses an instance of **BCryptPasswordEncoder**. For _older unsafe/no-encoding/default/unsecure_  behaviour get commit 36853b5c1338d17d81153e700f7f2f23acc21bd6.
