### ISSUE TITLE
error: package javax.annotation is not visible 

### ISSUE THREAD

**Issue by tuanvietus** [Apress/pro-spring-5#7]
Hi,

I'm hoping to get help with this error on building the project pro-spring-5 `gradle --refresh-dependencies clean build -x test` :

This project is a collection of simple code samples. It is meant to be used together with the "Spring Pro, Fifth Edition"  published by Apress in order to learn and practice with all Spring Web libraries. 

Task :chapter02:hello-world:compileJava
Note: /Users/viet/git/pro-spring-5/chapter02/hello-world/src/main/java/com/apress/prospring5/ch2/decoupled/MessageSupportFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Task :chapter03:collections:compileJava FAILED
/Users/viet/git/pro-spring-5/chapter03/collections/src/main/java/com/apress/prospring5/ch3/annotated/CollectionInjection.java:13: error: package javax.annotation is not visible
import javax.annotation.Resource;
            ^
  (package javax.annotation is declared in module java.xml.ws.annotation, which is not in the module graph)
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':chapter03:collections:compileJava'.
Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 29s
155 actionable tasks: 25 executed, 130 up-to-date

**Comment by iuliana** [comment]
Hello tuanvietus, 

Which branch are you trying to build? The master branch builds fully with Java 8 and Spring 5. the reason for this was that when writing the book Java 9 was not released yet. 
And when it was released it took some time for Spring 5 to support Java 9. And even if Spring 5 supported Java 9, a lot of the dependencies of the project didn't (and still don't). So the project is stuck on Java 8 unfortunately. 

The Java 9 examples in the book can be found on branch feature/java9 of the raw repository: https://github.com/iuliana/pro-spring-15. But be warned, the branch is unstable and only module chapter18 compiles. 

Let me know if everything is ok with Java 8. 
Cheers!

**Comment by tuanvietus** [comment]
Hi Iuliana,

Thanks for responding! I'm trying to build the master branch and upon your mentioning Java level, I've tried to set the project to use Java 8, then Java 9 in Intellij but I'm still getting the same error.

**Comment by iuliana** [comment]
Hi tuanvietus, 
If you get the same error, which is:
`(package javax.annotation is declared in module java.xml.ws.annotation, which is not in the module graph)`
Maybe JAVA_HOME is not set to Java 8. Java 8 should have no knowledge of modules. If you are building the project from the command line execute:
`java -version` 
and make sure the proper java version is used.
Good luck!

**Comment by tuanvietus** [comment]
You're right! My JAVA_HOME was at Java 9. I changed it back to Java 8 and it works. Thank you!

**Comment by tuanvietus** [comment]
You're right! My JAVA_HOME was at Java 9. I changed it back to Java 8 and it works. Thank you!
