### ISSUE TITLE
Small typos in Chapter 7

### ISSUE THREAD

**Issue by inponomarev** [Apress/pro-spring-5#9]
It seems that some old example that envolved contact/telephone database was not fully adapted for singers-albums database example.

* p. 373 'the statement `from Singer s` simply retrieves all contacts from database' should be 'all singers from database'
* p. 375 '`findAllWithAlbum()` method will retrieve all contact information together with their telephone details and hobbies' should be 'all singer information together with their albums and instruments'

**Comment by iuliana** [comment]
I will start corrections for this book at the end of September, I am not available until then. thank yopu very much for buying the book and for your contributions.

**Comment by iuliana** [comment]
Thank you for your contribution. The recommended correction have been added to the errata.

**Comment by iuliana** [comment]
I'll correct this as well, but please just make a list of typos and send it to me via email. Github is for problems in the code. Plus GitHub is spamming me. :)
